### ISSUE TITLE
Sync with PyPI releases

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/python-casacore-feedstock#14]
Hi,

I was wondering why this feedstock is not in sync with the PyPI releases of `python-casacore`?

Best regards,
Sebastian

**Comment by pkgw** [comment]
We needed to package a prerelease version of the library in order to be able to build NRAO CASA against the package, since NRAO CASA has/had the vexing habit of building against their own arbitrary python-casacore codebase rather than official release versions. That decoupled us from the system that automatically updates packages for new PyPI releases.

With CASA 6 coming down the line hopefully this will stop being an issue — and even if it doesn't, at a certain point we could decide that hacking the packaging here is not the solution we want to go with. I'd be OK with switching this feedstock to start tracking PyPI releases, and could draft a pull request to implement that if it would be valuable to you.

**Comment by sebastian-luna-valero** [comment]
Thanks @pkgw 

Switching this feedstock to start tracking PyPI releases would be great. I hope that's also beneficial for the community out there. Please let me know if I can help.

Best regards,
Sebastian

**Comment by pkgw** [comment]
OK, well Step 1 is to get casacore updating too. See: conda-forge/casacore-feedstock#43

**Comment by tammojan** [comment]
FYI I'm about to release a new python-casacore, with the very latest casacore 3.3.0 (released yesterday).

**Comment by tammojan** [comment]
I've made some changes to the setup.py logic to find boost-python and casacore, hopefully some of the patches here will not be necessary anymore. In particular the boost-python name should now be found automatically and the include path is passed on to the compiler, so setting `CPATH` should not be necessary anymore. I'm planning on releasing python-casacore 3.3.0 tomorrow after a bit more testing.

**Comment by pkgw** [comment]
I was just able to update us to 3.2.0 and strip out a lot of the custom junk in the recipe, so that all looks promising. Thanks @tammojan!

Now that we're on the PyPI, this feedstock *should* automatically update when 3.3.0 comes out ... so we should have a nice test case as to whether that bit has correctly kicked in too.

**Comment by sebastian-luna-valero** [comment]
Brilliant, thank you both!

**Comment by tammojan** [comment]
> Now that we're on the PyPI, this feedstock _should_ automatically update when 3.3.0 comes out ... so we should have a nice test case as to whether that bit has correctly kicked in too.

I think it worked, see #16!

**Comment by pkgw** [comment]
Yup! I just merged #16 so python-casacore 3.3.0 should be available for installation in about an hour.
