### ISSUE TITLE
Can we get a python 3.11 build?

### ISSUE THREAD

**Issue by bhazelton** [conda-forge/python-casacore-feedstock#30]
### Comment:

We'd like to start testing pyuvdata against python 3.11, but we need a python-casacore 3.11 build to do that.

Thanks!

**Comment by pkgw** [comment]
Just dug into this a bit — it appears that the underlying `casacore` library package was not migrating to Python 3.11 because the conda-forge migrator bot has trouble solving its dependencies relating to MPI. I've tried implementing a fix manually here:

https://github.com/conda-forge/casacore-feedstock/pull/74

If/when that works, I think it will be possible to migrate this package to Python 3.11 pretty quickly and straightforwardly.

**Comment by pkgw** [comment]
OK, that unlocked the bot to do its thing and everything seems happy here:

https://github.com/conda-forge/python-casacore-feedstock/pull/31

**Comment by bhazelton** [comment]
Thank you!!
